### ISSUE TITLE
Task3中在ubuntu中两个mem进程申请的内存不一样，但deepin中申请一样，why?

### ISSUE THREAD

**Issue by sunhanwu** [sunhanwu/16281047_OperatingSystemExperiment#2]
我的实验报告中的截图显示的是两次mem进程申请的是同一个物理地址，但是今天再次重复这个实验的时候发现申请的物理地址竟然不一样了。对此我提出我的假设：
操作系统中对于内存的管理是进行虚拟化管理的，就是假如实际内存不够用的话，就将多个进程分配相同的内存空间,使用虚拟化的技术对内存进行管理，但是如果实际内存够用的话，就分配不同的物理内存。不知道这种假设对不对，欢迎大家批评指正

**Comment by Neoyanghc** [comment]
不同系统不一样吧

**Comment by sunhanwu** [comment]
每个进程所用的内存均是虚拟内存，映射到实际的物理内存去都不一样，但是printf打印的是虚拟内存号，所以有可能相同，但是大部分时候应该不同
